name: Docker Build and Push

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_NAME }}:latest

      - name: Setup Docker CLI
        run: |
          mkdir -p ~/.docker/cli-plugins/
          wget https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -O ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV
          docker info

      - name: Run Docker in Docker to demonstrate DinD
        run: |
          docker run hello-world
          docker images
          docker ps -a